### ISSUE TITLE
[Role Request] Enabling/disabling secure boot	

### ISSUE THREAD

**Issue by Gal-Zaidman** [opiproject/ansible-opi-dpu#14]
Description:
Enables managing the state of the UEFI Secure Boot through the DPU Redfish interface.
This allows clients to set whether UEFI should authenticate the OS image during the boot process.
Input:
SecureBootEnable(bool)
Output:
Success/failure

Nvidia Docs example:
https://docs.nvidia.com/networking/display/bluefieldbmcv2310/bios+secure+boot+configuration#src-2506859311_BIOSSecureBootConfiguration-SettingSecureBootState

**Comment by glimchb** [comment]
see https://github.com/opiproject/ansible-opi-dpu/tree/main/roles/enable_secure_boot template code
